version: '3.8'
services:
  app:
    build: ./client
    env_file:
      - .env
  api:
    build: ./server
    env_file:
      - .env
  proxy:
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/prod:/etc/nginx/conf.d
    depends_on:
      - app
      - api
