version: '3.8'
services:
  app:
    image: "fhsshim/chookgu-app"
    mem_limit: 256m
    env_file:
      - .env
  api:
    image: "fhsshim/chookgu-api"
    mem_limit: 512m
    env_file:
      - .env
  proxy:
    image: "fhsshim/chookgu-proxy"
    mem_limit: 256m
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - api
