version: '3.8'
services:
  app:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules/
    env_file:
      - .env
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules/
    env_file:
      - .env
  proxy:
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d
    depends_on:
      - app
      - api

